### ISSUE TITLE
Create Delete mappping to delete a task

### ISSUE THREAD

**Issue by Shakthichaithanya** [Shakthichaithanya/todo#12]
Create a Delete mapping in TaskController to handle Delete request by taking Task unique id in path variable to delete the task in database.

RequestMethod: Delete
Request URL: /tasks/{id}

Response: json type

{
"status" : 200,
"message": "Task deleted successfully"
}

**Comment by choichanhyeok** [comment]
Hi bro can i solve this issue?

**Comment by Shakthichaithanya** [comment]
sure bro @choichanhyeok , you can

**Comment by Shakthichaithanya** [comment]
Thank you
